// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heat.proto

package heat;

public interface HeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:heat.HeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool heat = 1;</code>
   */
  boolean getHeat();
}
