// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heat.proto

package heat;

public final class HeatServiceImpl {
  private HeatServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heat_HeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heat_HeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heat_HeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heat_HeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heat_TemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heat_TemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heat_TemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heat_TemperatureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nheat.proto\022\004heat\"\033\n\013HeatRequest\022\014\n\004hea" +
      "t\030\001 \001(\010\"\034\n\014HeatResponse\022\014\n\004heat\030\001 \001(\010\"G\n" +
      "\022TemperatureRequest\022\017\n\007numbers\030\001 \001(\005\022\r\n\005" +
      "start\030\002 \001(\005\022\021\n\tincrement\030\003 \001(\005\"*\n\023Temper" +
      "atureResponse\022\023\n\013temperature\030\001 \001(\0052\222\001\n\013H" +
      "eatService\0225\n\nheatSwitch\022\021.heat.HeatRequ" +
      "est\032\022.heat.HeatResponse\"\000\022L\n\021changeTempe" +
      "rature\022\030.heat.TemperatureRequest\032\031.heat." +
      "TemperatureResponse\"\0000\001B\031\n\004heatB\017HeatSer" +
      "viceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_heat_HeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_heat_HeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heat_HeatRequest_descriptor,
        new java.lang.String[] { "Heat", });
    internal_static_heat_HeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_heat_HeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heat_HeatResponse_descriptor,
        new java.lang.String[] { "Heat", });
    internal_static_heat_TemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_heat_TemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heat_TemperatureRequest_descriptor,
        new java.lang.String[] { "Numbers", "Start", "Increment", });
    internal_static_heat_TemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_heat_TemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heat_TemperatureResponse_descriptor,
        new java.lang.String[] { "Temperature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
