// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heat.proto

package heat;

public interface SuggestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:heat.SuggestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>int32 temp = 2;</code>
   */
  int getTemp();
}
