// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heat.proto

package heat;

public interface TemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:heat.TemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numbers = 1;</code>
   */
  int getNumbers();

  /**
   * <code>int32 start = 2;</code>
   */
  int getStart();

  /**
   * <code>int32 increment = 3;</code>
   */
  int getIncrement();
}
