// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heat.proto

package heat;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:heat.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temperature = 1;</code>
   */
  int getTemperature();
}
