// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: light.proto

package light;

public interface BillRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:light.BillRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 reading = 1;</code>
   */
  int getReading();

  /**
   * <code>double price = 2;</code>
   */
  double getPrice();

  /**
   * <code>double discount = 3;</code>
   */
  double getDiscount();
}
