// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: light.proto

package light;

public interface BillResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:light.BillResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 reading = 1;</code>
   */
  int getReading();

  /**
   * <code>double bill = 2;</code>
   */
  double getBill();
}
