// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: light.proto

package light;

public interface ColourRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:light.ColourRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string colour = 1;</code>
   */
  java.lang.String getColour();
  /**
   * <code>string colour = 1;</code>
   */
  com.google.protobuf.ByteString
      getColourBytes();
}
