// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: light.proto

package light;

public final class LightServiceImpl {
  private LightServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_light_BillRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_light_BillRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_light_BillResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_light_BillResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_light_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_light_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_light_PowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_light_PowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_light_ColourRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_light_ColourRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_light_ColourResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_light_ColourResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013light.proto\022\005light\"?\n\013BillRequest\022\017\n\007r" +
      "eading\030\001 \001(\005\022\r\n\005price\030\002 \001(\001\022\020\n\010discount\030" +
      "\003 \001(\001\"-\n\014BillResponse\022\017\n\007reading\030\001 \001(\005\022\014" +
      "\n\004bill\030\002 \001(\001\"\035\n\014PowerRequest\022\r\n\005power\030\001 " +
      "\001(\010\"\036\n\rPowerResponse\022\r\n\005power\030\001 \001(\010\"\037\n\rC" +
      "olourRequest\022\016\n\006colour\030\001 \001(\t\" \n\016ColourRe" +
      "sponse\022\016\n\006colour\030\001 \001(\t2\313\001\n\014LightService\022" +
      ":\n\013powerSwitch\022\023.light.PowerRequest\032\024.li" +
      "ght.PowerResponse\"\000\022?\n\014changeColour\022\024.li" +
      "ght.ColourRequest\032\025.light.ColourResponse" +
      "\"\000(\001\022>\n\rcalculateBill\022\022.light.BillReques" +
      "t\032\023.light.BillResponse\"\000(\0010\001B\033\n\005lightB\020L" +
      "ightServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_light_BillRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_light_BillRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_light_BillRequest_descriptor,
        new java.lang.String[] { "Reading", "Price", "Discount", });
    internal_static_light_BillResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_light_BillResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_light_BillResponse_descriptor,
        new java.lang.String[] { "Reading", "Bill", });
    internal_static_light_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_light_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_light_PowerRequest_descriptor,
        new java.lang.String[] { "Power", });
    internal_static_light_PowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_light_PowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_light_PowerResponse_descriptor,
        new java.lang.String[] { "Power", });
    internal_static_light_ColourRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_light_ColourRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_light_ColourRequest_descriptor,
        new java.lang.String[] { "Colour", });
    internal_static_light_ColourResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_light_ColourResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_light_ColourResponse_descriptor,
        new java.lang.String[] { "Colour", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
