// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package security;

public interface AccessResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.AccessResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reply = 1;</code>
   */
  java.lang.String getReply();
  /**
   * <code>string reply = 1;</code>
   */
  com.google.protobuf.ByteString
      getReplyBytes();
}
