// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package security;

public interface SecurityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.SecurityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool security = 1;</code>
   */
  boolean getSecurity();
}
