// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package security;

public final class SecurityServiceImpl {
  private SecurityServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_SecurityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_SecurityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_SecurityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_SecurityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_ListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_ListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_ListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_AccessRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_AccessRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_security_AccessResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_security_AccessResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016security.proto\022\010security\"#\n\017SecurityRe" +
      "quest\022\020\n\010security\030\001 \001(\010\"$\n\020SecurityRespo" +
      "nse\022\020\n\010security\030\001 \001(\010\"\032\n\013ListRequest\022\013\n\003" +
      "ask\030\001 \001(\t\"\033\n\014ListResponse\022\013\n\003ans\030\001 \001(\t\")" +
      "\n\rAccessRequest\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(" +
      "\t\"\037\n\016AccessResponse\022\r\n\005reply\030\001 \001(\t2\342\001\n\017S" +
      "ecurityService\022I\n\016securitySwitch\022\031.secur" +
      "ity.SecurityRequest\032\032.security.SecurityR" +
      "esponse\"\000\022>\n\tListstaff\022\025.security.ListRe" +
      "quest\032\026.security.ListResponse\"\0000\001\022D\n\013gra" +
      "ntAccess\022\027.security.AccessRequest\032\030.secu" +
      "rity.AccessResponse\"\000(\001B!\n\010securityB\023Sec" +
      "urityServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_security_SecurityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_security_SecurityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_SecurityRequest_descriptor,
        new java.lang.String[] { "Security", });
    internal_static_security_SecurityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_security_SecurityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_SecurityResponse_descriptor,
        new java.lang.String[] { "Security", });
    internal_static_security_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_security_ListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_ListRequest_descriptor,
        new java.lang.String[] { "Ask", });
    internal_static_security_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_security_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_ListResponse_descriptor,
        new java.lang.String[] { "Ans", });
    internal_static_security_AccessRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_security_AccessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_AccessRequest_descriptor,
        new java.lang.String[] { "Name", "Id", });
    internal_static_security_AccessResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_security_AccessResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_security_AccessResponse_descriptor,
        new java.lang.String[] { "Reply", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
