// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package security;

public interface SecurityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.SecurityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool security = 1;</code>
   */
  boolean getSecurity();
}
